#!/bin/bash
# Copyright (C) 2012 Bernhard Heinloth <bernhard@heinloth.net>
# Copyright (C) 2012 Valentin Rothberg <valentinrothberg@gmail.com>
# Copyright (C) 2012-2017 Andreas Ziegler <ziegler@einserver.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
set -e

TRACEUTIL=undertaker-traceutil
SCRIPTDIRINSTALLED="$(dirname "$(readlink -f "$0")")/../lib/undertaker/tailor/ubuntu-boot"
SCRIPTDIR="$(dirname "$(readlink -f "$0")")/boot"
FORCE=false

INITRAMFS="$(mktemp)"
INITRD="$(mktemp)"
INITSYSTEM="systemd"

function help {
    echo "Usage $0 [arguments]"
    echo
    echo "Possible arguments:"
    echo "  -s <dir>    Path to dir with bootscripts"
    echo "  -t <file>   Path to trace util excecutable"
    echo "  -i <init>   Init system used, can be 'systemd' or 'upstart'. Default: 'systemd'"
    echo "  -h          Print this help"
    echo "  -f          Force the actions"
}

while getopts "fs:t:i:h" options ; do
    case "$options" in
        h)  help
            exit 0
            ;;
        f)  FORCE=true
            ;;
        s)  if [[ -d "$OPTARG" ]] ; then
                SCRIPTDIR="$OPTARG"
            else
                echo "scriptdir '$OPTARG' is not a directory - aborting"
                exit 1
            fi
            ;;
        t)  if [[ -x "$OPTARG" ]] ; then
                TRACEUTIL="$(readlink -f "$OPTARG" )"
            else
                echo "traceutil '$OPTARG' is not an executable file - aborting"
                exit 1
            fi
            ;;
        i)  INITSYSTEM="$OPTARG"
            if [[ "$INITSYSTEM" != "systemd" && "$INITSYSTEM" != "upstart" ]] ; then
                echo "Supported init systems are 'upstart' and 'systemd'"
                exit 1
            fi
            ;;
        *)  echo "Unknown Argument..."
            help
            exit 1
            ;;
    esac
done

if [[ "$FORCE" = "false" ]] ; then
    if ! which lsb_release > /dev/null 2>&1 || [[ "$(lsb_release -i -s)" != "Ubuntu" ]] ; then
        echo "This is not Ubuntu..."
        exit 1
    fi
fi

if [[ ! -d "$SCRIPTDIR" ]] ; then
    if [[ -d "$SCRIPTDIRINSTALLED" ]] ; then
        SCRIPTDIR="$SCRIPTDIRINSTALLED"
    else
        echo "Could not find scriptdir at $SCRIPTDIR - aborting..."
        exit 1
    fi
fi

# Check for presence of traceutil
if [[ ! -x "$TRACEUTIL" ]] ; then
    TRACEUTIL="$(type -P "$TRACEUTIL")"
fi
if [[ -z "$TRACEUTIL" || ! -x "$TRACEUTIL" ]] ; then
    echo "ERROR: undertaker-traceutil was not found."
    echo "If you only downloaded and\
 compiled the undertaker sources, please provide the -t parameter with the\
 path to the compiled undertaker-traceutil binary."
    exit 1
fi

# Warn the user if they are not root that things will fail
if [[ "$FORCE" = "false" && "$(id -u)" != "0" ]] ; then
    echo "WARNING: You are not root."
    echo "Some of the following commands will likely fail."
fi

# If traceutil is not in the right spot, copy it there or issue warning
if [[ "$FORCE" = "true" || ( "$(id -u)" = "0" && "$TRACEUTIL" != "/usr/sbin/undertaker-traceutil" ) ]] ; then
    cp -v "$TRACEUTIL" /usr/sbin/undertaker-traceutil
elif [[ "$(id -u)" != "0" ]] ; then
    echo "Please make sure that \"$TRACEUTIL\" is located at /usr/sbin/ to use\
 early boot tracing. If it is not, copy it there yourself!"
fi

if [[ "$INITSYSTEM" = "upstart" ]]; then
    # Copy configuration file to /etc/init
    if [[ "$FORCE" = "true" || "$(id -u)" = "0" ]] ; then
        cp -v "$SCRIPTDIR/undertaker-trace.conf" /etc/init/undertaker-trace.conf
    else
        echo "WARNING: $SCRIPTDIR/undertaker-trace.conf could not be copied to /etc/init."
        echo "     You MUST do this if early boot tracing is desired!"
    fi
else
    # Systemd: copy to /etc/systemd/system/
    if [[ "$FORCE" = "true" || "$(id -u)" = "0" ]] ; then
        cp -v "$SCRIPTDIR/undertaker-trace.service" /etc/systemd/system/undertaker-trace.service
        systemctl enable undertaker-trace.service
    else
        echo "WARNING: $SCRIPTDIR/undertaker-trace.service could not be copied to /etc/systemd/system."
        echo "     You MUST do this if early boot tracing is desired!"
    fi
fi

# Create initrd in local directory, try to copy it to /boot afterwards
cd "$SCRIPTDIR"
zcat "/boot/initrd.img-$(uname -r)" | cpio -uid --quiet "scripts/init-bottom/ORDER"
echo "/scripts/init-bottom/start-ftrace" \
    | cat - "scripts/init-bottom/ORDER" > "scripts/init-bottom/ORDER.tmp" \
    && mv "scripts/init-bottom/ORDER.tmp" "scripts/init-bottom/ORDER"
find scripts/ | grep -v .svn | cpio -ov --format=newc | gzip -9 > "$INITRAMFS"
cd "$OLDPWD"
cat "/boot/initrd.img-$(uname -r)" "$INITRAMFS" > "$INITRD"

# This needs root, otherwise warn user to copy the file.
if [[ "$FORCE" = "true" || "$(id -u)" = "0" ]] ; then
    cp -v "$INITRD" "/boot/initrd.img-$(uname -r).ftrace"
else
    cp -v "$INITRD" "./initrd.img-$(uname -r).ftrace"
    echo "WARNING: You are not root, new initrd created as ./initrd.img-$(uname -r).ftrace."
    echo "Please copy it to /boot as root."
fi
